/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sticker.frontend;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jovan
 */
public class StickerClientMainWindow extends javax.swing.JFrame {

    private static final String USERNAME_KEYWORD = "MyUserName:";
    private static final String REMOVED_MISSING_KEYWORD = "RemovedMissing:";
    private static final String REMOVED_DUPLICATES_KEYWORD = "RemovedDuplicates:";
    private static final String EXCHANGE_POSSIBILITIES_REQ_KEYWORD = "ExchangePossibilities.";
    
    private Socket socket;
    private BufferedReader br;
    private PrintWriter pw;
    private ReceiveMessageFromServer rmfs;
    private String userName;
    
    private StickerCollection missingStickersUI;
    private StickerCollection duplicateStickersUI;
    
    public BufferedReader getBr() {
        return br;
    }
    
    public StickerCollection getMissingStickersUI() {
        return missingStickersUI;
    }
    
    public StickerCollection getDuplicateStickersUI() {
        return duplicateStickersUI;
    }
    
    public String getUserName() {
        return userName;
    }
    
    public void setUsername(String username) {
        this.userName = username;
    }
    
    public void appendUser(String name) {
        comboExchange.addItem(name);
    }
    
    /**
     * Creates new form StickerClientMainWindow
     */
    public StickerClientMainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnect = new javax.swing.JButton();
        btnSendUserName = new javax.swing.JButton();
        tfMyName = new javax.swing.JTextField();
        btnExchangePossibilities = new javax.swing.JButton();
        comboExchange = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConnect.setText("Konektuj se");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnSendUserName.setText("Registruj se");
        btnSendUserName.setEnabled(false);
        btnSendUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendUserNameActionPerformed(evt);
            }
        });

        tfMyName.setEnabled(false);

        btnExchangePossibilities.setText("Moguce zamene");
        btnExchangePossibilities.setEnabled(false);
        btnExchangePossibilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExchangePossibilitiesActionPerformed(evt);
            }
        });

        comboExchange.setEnabled(false);
        comboExchange.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConnect)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendUserName)
                            .addComponent(btnExchangePossibilities))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(comboExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExchangePossibilities)
                    .addComponent(comboExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendUserName)
                    .addComponent(tfMyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConnect)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        try {
            this.socket = new Socket("127.0.0.1", 6001);
            this.br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
            this.pw = new PrintWriter(new OutputStreamWriter(this.socket.getOutputStream()), true);
            
            this.missingStickersUI = new StickerCollection("Slicice koje mi nedostaju", this.pw, REMOVED_MISSING_KEYWORD);
            this.duplicateStickersUI = new StickerCollection("Slicice koje imam viska", this.pw, REMOVED_DUPLICATES_KEYWORD);

            this.rmfs = new ReceiveMessageFromServer(this);
            Thread thr = new Thread(rmfs);
            thr.start();

            btnConnect.setEnabled(false);
            btnSendUserName.setEnabled(true);
            tfMyName.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(StickerClientMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnSendUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendUserNameActionPerformed

        if (!tfMyName.getText().equals("")) {
            tfMyName.setEnabled(false);
            btnSendUserName.setEnabled(false);
            
            userName = tfMyName.getText();
            this.setTitle("MENJAZA " + userName);
            missingStickersUI.setTitle(missingStickersUI.getTitle() + " (" + userName + ")");
            duplicateStickersUI.setTitle(duplicateStickersUI.getTitle() + " (" + userName + ")");
            
            missingStickersUI.setVisible(true);
            duplicateStickersUI.setVisible(true);
            
            comboExchange.setEnabled(true);
            btnExchangePossibilities.setEnabled(true);
            
            pw.println(USERNAME_KEYWORD + userName);
        }
    }//GEN-LAST:event_btnSendUserNameActionPerformed

    private void btnExchangePossibilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExchangePossibilitiesActionPerformed
        pw.println(EXCHANGE_POSSIBILITIES_REQ_KEYWORD);
    }//GEN-LAST:event_btnExchangePossibilitiesActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StickerClientMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StickerClientMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StickerClientMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StickerClientMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StickerClientMainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnExchangePossibilities;
    private javax.swing.JButton btnSendUserName;
    private javax.swing.JComboBox<String> comboExchange;
    private javax.swing.JTextField tfMyName;
    // End of variables declaration//GEN-END:variables
}
